### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Lukas-Batema**
I don't know why vscode is merging commits this way but is there anything I can do to fix it?

### CODE REVIEW

**Comment by theopcoder** [comment]
Is this a pull request or an issue

**Comment by theopcoder** [comment]
also, if you have the GitHub desktop app, you can pull the requests to the project

**Comment by Lukas-Batema** [comment]
> Is this a pull request or an issue

It’s a pr

**Comment by theopcoder** [comment]
The reason I asked is because all the commits where already merged and this sounds more like an issue

**Comment by Lukas-Batema** [comment]
> The reason I asked is because all the commits where already merged and this sounds more like an issue

Ya, VSCode on Mac might be pretty wack, I will see what I can do when I get on later

**Comment by Lukas-Batema** [comment]
imma close this and try to fix it

**Pull request closed without merging**
