### PR TITLE
2.1.3 Feature Update

### PR DESCRIPTION
**Pull request by Lukas-Batema**
I decided to add a command about cubing, which the syntax is, "rubricx qewbz,' which outputs, "My friend can solve that in like 2 seconds!" I realized I messed up the syntax of JavaScript, so I will fix that before merging.

I added the wiki link to the new member joining message as well. [Pedestriapedia Official](https://wiki.pedestriamc.com/)

Also, I removed all the references to staff applications that I could find, because the owner of the server which this bot presides, prefers a different method of creating staff applications.

Lastly, I changed the activity message to, "play.pedestriamc.com | The Official WIki for PedestriaMC Network is now released!"

### CODE REVIEW

**Comment by Lukas-Batema** [comment]
I just fixed the syntax, should be good to merge, if you want!

**Comment by Lukas-Batema** [comment]
I added some status messages and updated the Changelog.

**Review by theopcoder — APPROVED** [review]
It's ready for a merge!

**Review by theopcoder — APPROVED** [review]
All good

**Pull request merged**
