### PR TITLE
Fixed Spelling Mistake

### PR DESCRIPTION
**Pull request by sltan1020**
#12  spelling mistake in README.md #11

### CODE REVIEW

**Comment by Lukas-Batema** [comment]
This has no files being added/changed, what are you trying to do then?

**Comment by sltan1020** [comment]
> 4AEE18F83AFDEB23

**Comment by Lukas-Batema** [comment]
> 4AEE18F83AFDEB23

That has already been fixed though.

**Comment by Lukas-Batema** [comment]
I still do not know what you are trying to change. I checked the README.md, and all seems fine, as well as the development branch is for testing, not the main branch.

**Review by sltan1020 — COMMENTED** [review]
ff

**Pull request closed without merging**
